create database ak;
use ak;
CREATE TABLE AKSHAT(
RollNo INT PRIMARY KEY,
STUDENT_NAME VARCHAR(20) NOT NULL,
BRANCH VARCHAR(20),
AGE INT,
CITY VARCHAR(20)); 
INSERT INTO AKSHAT VALUES (1, 'Akshat', 'CSE', 20, 'Faridabad');
INSERT INTO AKSHAT VALUES (2, 'Rahul', 'ECE', 21, 'Delhi');
INSERT INTO AKSHAT VALUES (3, 'Priya', 'CSE', 19, 'Noida');
INSERT INTO AKSHAT VALUES (4, 'Neha', 'ME', 22, 'Gurgaon');
INSERT INTO AKSHAT VALUES (5, 'Arjun', 'EEE', 23, 'Faridabad');
INSERT INTO AKSHAT VALUES (6, 'Meera', 'CSE', 20, 'Delhi');
INSERT INTO AKSHAT VALUES (7, 'Ravi', 'ECE', 21, 'Noida');
INSERT INTO AKSHAT VALUES (8, 'Sita', 'ME', 22, 'Faridabad');
INSERT INTO AKSHAT VALUES (9, 'Vikas', 'CSE', 24, 'Delhi');
INSERT INTO AKSHAT VALUES (10, 'Kavita', 'EEE', 25, 'Gurgaon');
SELECT * FROM AKSHAT;
-- (i) USING AND OPERATOR
SELECT * FROM AKSHAT WHERE BRANCH='CSE' AND AGE=20;
-- (ii) USING OR OPERATOR
SELECT * FROM AKSHAT WHERE CITY='Delhi' OR CITY='Noida';
-- (iii) USING BETWEEN OPERATOR
SELECT * FROM AKSHAT WHERE AGE BETWEEN 20 AND 23;
-- (iv) USING NULL/NOT NULL OPERATOR
SELECT * FROM AKSHAT WHERE CITY IS NOT NULL;
-- (V) USING AGGREGATE FUNCTIONS
SELECT SUM(AGE) FROM AKSHAT;
SELECT MIN(AGE) FROM AKSHAT;
SELECT MAX(AGE) FROM AKSHAT;
SELECT AVG(AGE) FROM AKSHAT;
SELECT COUNT(*) FROM AKSHAT;
SELECT ROUND(AVG(AGE),2) FROM AKSHAT;
SELECT COUNT(DISTINCT CITY) FROM AKSHAT;